### PR TITLE
llvm 13

### PR DESCRIPTION
**Pull request by chriku**
Started compatibility for llvm 13 (tried on debian).

~~Tests are still failing (allocating enormous amounts of memory)~~

### CODE REVIEW

**Comment by elliottslaughter** [comment]
Thanks for doing this! Looks like the CI passed. I will plan to wait for the official LLVM 13 release so that we can use the official binaries in our CI tests, but will merge it once those become available and CI confirms that LLVM 13 final passes.

**Comment by chriku** [comment]
It seems the g++ in the pipeline for ubuntu bionic builds with `-std=c++11` while `-std=c++14` would be needed for llvm 13

**Comment by chriku** [comment]
Seems like my github actions are finally able to run the current version. MacOS has to be reenabled, as soon as https://github.com/elliottslaughter/llvm-build contains LLVM 13

**Comment by chriku** [comment]
LLVM 13 seems to be out now (github has the release). This branch disable the macOS version, but I hope @elliottslaughter can bump https://github.com/elliottslaughter/llvm-build to the final release.

**Comment by elliottslaughter** [comment]
Mac build is up. You should be able to update the PR to test it now.

**Comment by chriku** [comment]
Pipeline is stuck with
```
Can't find any online and idle self-hosted runner in the current repository, account/organization that matches the required labels: 'ubuntu-16.04'
Waiting for a self-hosted runner to pickup this job...
```
Is there a connection to #506? Should I set up a self hosted runner for this PR?

**Comment by elliottslaughter** [comment]
Merged. I'll sort out the CI on my end; should be possible to get LLVM 3.8 on a newer Ubuntu.

Thanks again for all your work on this!

**Pull request merged**
